require: rubocop-rspec

inherit_from: todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2

Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/RequireParentheses:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'bin/deploy'
    - 'spec/factories.rb'

Rails:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'app/views/**/*'

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

# Don't turn this on, it's overzealous
Style/MethodCallWithArgsParentheses:
  Enabled: false
